pycket-c sumfp-fixflo.rkt  >> /scratch1/magnus/trace_output/sumfp-fixflo.rkt.out 2>&1
pycket-c sumfp-fixflo.rkt  >> /scratch1/magnus/trace_output/sumfp-fixflo.rkt.out 2>&1
pycket-c sumfp-fixflo.rkt  >> /scratch1/magnus/trace_output/sumfp-fixflo.rkt.out 2>&1
pycket-c slatex-nothing.rkt  >> /scratch1/magnus/trace_output/slatex-nothing.rkt.out 2>&1
pycket-c slatex-nothing.rkt  >> /scratch1/magnus/trace_output/slatex-nothing.rkt.out 2>&1
pycket-c slatex-nothing.rkt  >> /scratch1/magnus/trace_output/slatex-nothing.rkt.out 2>&1
pycket-c sumloop-nothing.rkt  >> /scratch1/magnus/trace_output/sumloop-nothing.rkt.out 2>&1
pycket-c sumloop-nothing.rkt  >> /scratch1/magnus/trace_output/sumloop-nothing.rkt.out 2>&1
pycket-c sumloop-nothing.rkt  >> /scratch1/magnus/trace_output/sumloop-nothing.rkt.out 2>&1
pycket-c tak-fixflo.rkt  >> /scratch1/magnus/trace_output/tak-fixflo.rkt.out 2>&1
pycket-c tak-fixflo.rkt  >> /scratch1/magnus/trace_output/tak-fixflo.rkt.out 2>&1
pycket-c tak-fixflo.rkt  >> /scratch1/magnus/trace_output/tak-fixflo.rkt.out 2>&1
pycket-c pi-fixflo.rkt  >> /scratch1/magnus/trace_output/pi-fixflo.rkt.out 2>&1
pycket-c pi-fixflo.rkt  >> /scratch1/magnus/trace_output/pi-fixflo.rkt.out 2>&1
pycket-c pi-fixflo.rkt  >> /scratch1/magnus/trace_output/pi-fixflo.rkt.out 2>&1
pycket-c perm9-nothing.rkt  >> /scratch1/magnus/trace_output/perm9-nothing.rkt.out 2>&1
pycket-c perm9-nothing.rkt  >> /scratch1/magnus/trace_output/perm9-nothing.rkt.out 2>&1
pycket-c perm9-nothing.rkt  >> /scratch1/magnus/trace_output/perm9-nothing.rkt.out 2>&1
pycket-c tail-fixflo.rkt  >> /scratch1/magnus/trace_output/tail-fixflo.rkt.out 2>&1
pycket-c tail-fixflo.rkt  >> /scratch1/magnus/trace_output/tail-fixflo.rkt.out 2>&1
pycket-c tail-fixflo.rkt  >> /scratch1/magnus/trace_output/tail-fixflo.rkt.out 2>&1
pycket-c tak-nothing.rkt  >> /scratch1/magnus/trace_output/tak-nothing.rkt.out 2>&1
pycket-c tak-nothing.rkt  >> /scratch1/magnus/trace_output/tak-nothing.rkt.out 2>&1
pycket-c tak-nothing.rkt  >> /scratch1/magnus/trace_output/tak-nothing.rkt.out 2>&1
pycket-c lattice-fixflo.rkt  >> /scratch1/magnus/trace_output/lattice-fixflo.rkt.out 2>&1
pycket-c lattice-fixflo.rkt  >> /scratch1/magnus/trace_output/lattice-fixflo.rkt.out 2>&1
pycket-c lattice-fixflo.rkt  >> /scratch1/magnus/trace_output/lattice-fixflo.rkt.out 2>&1
pycket-c fft-nothing.rkt  >> /scratch1/magnus/trace_output/fft-nothing.rkt.out 2>&1
pycket-c fft-nothing.rkt  >> /scratch1/magnus/trace_output/fft-nothing.rkt.out 2>&1
pycket-c fft-nothing.rkt  >> /scratch1/magnus/trace_output/fft-nothing.rkt.out 2>&1
pycket-c gcold-fixflo.rkt  >> /scratch1/magnus/trace_output/gcold-fixflo.rkt.out 2>&1
pycket-c gcold-fixflo.rkt  >> /scratch1/magnus/trace_output/gcold-fixflo.rkt.out 2>&1
pycket-c gcold-fixflo.rkt  >> /scratch1/magnus/trace_output/gcold-fixflo.rkt.out 2>&1
pycket-c trav1-nothing.rkt  >> /scratch1/magnus/trace_output/trav1-nothing.rkt.out 2>&1
pycket-c trav1-nothing.rkt  >> /scratch1/magnus/trace_output/trav1-nothing.rkt.out 2>&1
pycket-c trav1-nothing.rkt  >> /scratch1/magnus/trace_output/trav1-nothing.rkt.out 2>&1
pycket-c mazefun-fixflo.rkt  >> /scratch1/magnus/trace_output/mazefun-fixflo.rkt.out 2>&1
pycket-c mazefun-fixflo.rkt  >> /scratch1/magnus/trace_output/mazefun-fixflo.rkt.out 2>&1
pycket-c mazefun-fixflo.rkt  >> /scratch1/magnus/trace_output/mazefun-fixflo.rkt.out 2>&1
pycket-c trav2-nothing.rkt  >> /scratch1/magnus/trace_output/trav2-nothing.rkt.out 2>&1
pycket-c trav2-nothing.rkt  >> /scratch1/magnus/trace_output/trav2-nothing.rkt.out 2>&1
pycket-c trav2-nothing.rkt  >> /scratch1/magnus/trace_output/trav2-nothing.rkt.out 2>&1
pycket-c cat-fixflo.rkt  >> /scratch1/magnus/trace_output/cat-fixflo.rkt.out 2>&1
pycket-c cat-fixflo.rkt  >> /scratch1/magnus/trace_output/cat-fixflo.rkt.out 2>&1
pycket-c cat-fixflo.rkt  >> /scratch1/magnus/trace_output/cat-fixflo.rkt.out 2>&1
pycket-c pnpoly-nothing.rkt  >> /scratch1/magnus/trace_output/pnpoly-nothing.rkt.out 2>&1
pycket-c pnpoly-nothing.rkt  >> /scratch1/magnus/trace_output/pnpoly-nothing.rkt.out 2>&1
pycket-c pnpoly-nothing.rkt  >> /scratch1/magnus/trace_output/pnpoly-nothing.rkt.out 2>&1
pycket-c ray-nothing.rkt  >> /scratch1/magnus/trace_output/ray-nothing.rkt.out 2>&1
pycket-c ray-nothing.rkt  >> /scratch1/magnus/trace_output/ray-nothing.rkt.out 2>&1
pycket-c ray-nothing.rkt  >> /scratch1/magnus/trace_output/ray-nothing.rkt.out 2>&1
pycket-c lattice-nothing.rkt  >> /scratch1/magnus/trace_output/lattice-nothing.rkt.out 2>&1
pycket-c lattice-nothing.rkt  >> /scratch1/magnus/trace_output/lattice-nothing.rkt.out 2>&1
pycket-c lattice-nothing.rkt  >> /scratch1/magnus/trace_output/lattice-nothing.rkt.out 2>&1
pycket-c primes-nothing.rkt  >> /scratch1/magnus/trace_output/primes-nothing.rkt.out 2>&1
pycket-c primes-nothing.rkt  >> /scratch1/magnus/trace_output/primes-nothing.rkt.out 2>&1
pycket-c primes-nothing.rkt  >> /scratch1/magnus/trace_output/primes-nothing.rkt.out 2>&1
pycket-c wc-nothing.rkt  >> /scratch1/magnus/trace_output/wc-nothing.rkt.out 2>&1
pycket-c wc-nothing.rkt  >> /scratch1/magnus/trace_output/wc-nothing.rkt.out 2>&1
pycket-c wc-nothing.rkt  >> /scratch1/magnus/trace_output/wc-nothing.rkt.out 2>&1
pycket-c paraffins-nothing.rkt  >> /scratch1/magnus/trace_output/paraffins-nothing.rkt.out 2>&1
pycket-c paraffins-nothing.rkt  >> /scratch1/magnus/trace_output/paraffins-nothing.rkt.out 2>&1
pycket-c paraffins-nothing.rkt  >> /scratch1/magnus/trace_output/paraffins-nothing.rkt.out 2>&1
pycket-c mbrot-fixflo.rkt  >> /scratch1/magnus/trace_output/mbrot-fixflo.rkt.out 2>&1
pycket-c mbrot-fixflo.rkt  >> /scratch1/magnus/trace_output/mbrot-fixflo.rkt.out 2>&1
pycket-c mbrot-fixflo.rkt  >> /scratch1/magnus/trace_output/mbrot-fixflo.rkt.out 2>&1
pycket-c nqueens-fixflo.rkt  >> /scratch1/magnus/trace_output/nqueens-fixflo.rkt.out 2>&1
pycket-c nqueens-fixflo.rkt  >> /scratch1/magnus/trace_output/nqueens-fixflo.rkt.out 2>&1
pycket-c nqueens-fixflo.rkt  >> /scratch1/magnus/trace_output/nqueens-fixflo.rkt.out 2>&1
pycket-c string-nothing.rkt  >> /scratch1/magnus/trace_output/string-nothing.rkt.out 2>&1
pycket-c string-nothing.rkt  >> /scratch1/magnus/trace_output/string-nothing.rkt.out 2>&1
pycket-c string-nothing.rkt  >> /scratch1/magnus/trace_output/string-nothing.rkt.out 2>&1
pycket-c cpstak-fixflo.rkt  >> /scratch1/magnus/trace_output/cpstak-fixflo.rkt.out 2>&1
pycket-c cpstak-fixflo.rkt  >> /scratch1/magnus/trace_output/cpstak-fixflo.rkt.out 2>&1
pycket-c cpstak-fixflo.rkt  >> /scratch1/magnus/trace_output/cpstak-fixflo.rkt.out 2>&1
pycket-c scheme-nothing.rkt  >> /scratch1/magnus/trace_output/scheme-nothing.rkt.out 2>&1
pycket-c scheme-nothing.rkt  >> /scratch1/magnus/trace_output/scheme-nothing.rkt.out 2>&1
pycket-c scheme-nothing.rkt  >> /scratch1/magnus/trace_output/scheme-nothing.rkt.out 2>&1
pycket-c maze-fixflo.rkt  >> /scratch1/magnus/trace_output/maze-fixflo.rkt.out 2>&1
pycket-c maze-fixflo.rkt  >> /scratch1/magnus/trace_output/maze-fixflo.rkt.out 2>&1
pycket-c maze-fixflo.rkt  >> /scratch1/magnus/trace_output/maze-fixflo.rkt.out 2>&1
pycket-c graphs-fixflo.rkt  >> /scratch1/magnus/trace_output/graphs-fixflo.rkt.out 2>&1
pycket-c graphs-fixflo.rkt  >> /scratch1/magnus/trace_output/graphs-fixflo.rkt.out 2>&1
pycket-c graphs-fixflo.rkt  >> /scratch1/magnus/trace_output/graphs-fixflo.rkt.out 2>&1
pycket-c slatex-fixflo.rkt  >> /scratch1/magnus/trace_output/slatex-fixflo.rkt.out 2>&1
pycket-c slatex-fixflo.rkt  >> /scratch1/magnus/trace_output/slatex-fixflo.rkt.out 2>&1
pycket-c slatex-fixflo.rkt  >> /scratch1/magnus/trace_output/slatex-fixflo.rkt.out 2>&1
pycket-c simplex-nothing.rkt  >> /scratch1/magnus/trace_output/simplex-nothing.rkt.out 2>&1
pycket-c simplex-nothing.rkt  >> /scratch1/magnus/trace_output/simplex-nothing.rkt.out 2>&1
pycket-c simplex-nothing.rkt  >> /scratch1/magnus/trace_output/simplex-nothing.rkt.out 2>&1
pycket-c conform-fixflo.rkt  >> /scratch1/magnus/trace_output/conform-fixflo.rkt.out 2>&1
pycket-c conform-fixflo.rkt  >> /scratch1/magnus/trace_output/conform-fixflo.rkt.out 2>&1
pycket-c conform-fixflo.rkt  >> /scratch1/magnus/trace_output/conform-fixflo.rkt.out 2>&1
pycket-c mazefun-nothing.rkt  >> /scratch1/magnus/trace_output/mazefun-nothing.rkt.out 2>&1
pycket-c mazefun-nothing.rkt  >> /scratch1/magnus/trace_output/mazefun-nothing.rkt.out 2>&1
pycket-c mazefun-nothing.rkt  >> /scratch1/magnus/trace_output/mazefun-nothing.rkt.out 2>&1
pycket-c string-fixflo.rkt  >> /scratch1/magnus/trace_output/string-fixflo.rkt.out 2>&1
pycket-c string-fixflo.rkt  >> /scratch1/magnus/trace_output/string-fixflo.rkt.out 2>&1
pycket-c string-fixflo.rkt  >> /scratch1/magnus/trace_output/string-fixflo.rkt.out 2>&1
pycket-c sum-nothing.rkt  >> /scratch1/magnus/trace_output/sum-nothing.rkt.out 2>&1
pycket-c sum-nothing.rkt  >> /scratch1/magnus/trace_output/sum-nothing.rkt.out 2>&1
pycket-c sum-nothing.rkt  >> /scratch1/magnus/trace_output/sum-nothing.rkt.out 2>&1
pycket-c sum-fixflo.rkt  >> /scratch1/magnus/trace_output/sum-fixflo.rkt.out 2>&1
pycket-c sum-fixflo.rkt  >> /scratch1/magnus/trace_output/sum-fixflo.rkt.out 2>&1
pycket-c sum-fixflo.rkt  >> /scratch1/magnus/trace_output/sum-fixflo.rkt.out 2>&1
pycket-c peval-nothing.rkt  >> /scratch1/magnus/trace_output/peval-nothing.rkt.out 2>&1
pycket-c peval-nothing.rkt  >> /scratch1/magnus/trace_output/peval-nothing.rkt.out 2>&1
pycket-c peval-nothing.rkt  >> /scratch1/magnus/trace_output/peval-nothing.rkt.out 2>&1
pycket-c triangl-nothing.rkt  >> /scratch1/magnus/trace_output/triangl-nothing.rkt.out 2>&1
pycket-c triangl-nothing.rkt  >> /scratch1/magnus/trace_output/triangl-nothing.rkt.out 2>&1
pycket-c triangl-nothing.rkt  >> /scratch1/magnus/trace_output/triangl-nothing.rkt.out 2>&1
pycket-c gcold-nothing.rkt  >> /scratch1/magnus/trace_output/gcold-nothing.rkt.out 2>&1
pycket-c gcold-nothing.rkt  >> /scratch1/magnus/trace_output/gcold-nothing.rkt.out 2>&1
pycket-c gcold-nothing.rkt  >> /scratch1/magnus/trace_output/gcold-nothing.rkt.out 2>&1
pycket-c trav1-fixflo.rkt  >> /scratch1/magnus/trace_output/trav1-fixflo.rkt.out 2>&1
pycket-c trav1-fixflo.rkt  >> /scratch1/magnus/trace_output/trav1-fixflo.rkt.out 2>&1
pycket-c trav1-fixflo.rkt  >> /scratch1/magnus/trace_output/trav1-fixflo.rkt.out 2>&1
pycket-c gcbench-nothing.rkt  >> /scratch1/magnus/trace_output/gcbench-nothing.rkt.out 2>&1
pycket-c gcbench-nothing.rkt  >> /scratch1/magnus/trace_output/gcbench-nothing.rkt.out 2>&1
pycket-c gcbench-nothing.rkt  >> /scratch1/magnus/trace_output/gcbench-nothing.rkt.out 2>&1
pycket-c trav2-fixflo.rkt  >> /scratch1/magnus/trace_output/trav2-fixflo.rkt.out 2>&1
pycket-c trav2-fixflo.rkt  >> /scratch1/magnus/trace_output/trav2-fixflo.rkt.out 2>&1
pycket-c trav2-fixflo.rkt  >> /scratch1/magnus/trace_output/trav2-fixflo.rkt.out 2>&1
pycket-c pnpoly-fixflo.rkt  >> /scratch1/magnus/trace_output/pnpoly-fixflo.rkt.out 2>&1
pycket-c pnpoly-fixflo.rkt  >> /scratch1/magnus/trace_output/pnpoly-fixflo.rkt.out 2>&1
pycket-c pnpoly-fixflo.rkt  >> /scratch1/magnus/trace_output/pnpoly-fixflo.rkt.out 2>&1
pycket-c peval-fixflo.rkt  >> /scratch1/magnus/trace_output/peval-fixflo.rkt.out 2>&1
pycket-c peval-fixflo.rkt  >> /scratch1/magnus/trace_output/peval-fixflo.rkt.out 2>&1
pycket-c peval-fixflo.rkt  >> /scratch1/magnus/trace_output/peval-fixflo.rkt.out 2>&1
pycket-c primes-fixflo.rkt  >> /scratch1/magnus/trace_output/primes-fixflo.rkt.out 2>&1
pycket-c primes-fixflo.rkt  >> /scratch1/magnus/trace_output/primes-fixflo.rkt.out 2>&1
pycket-c primes-fixflo.rkt  >> /scratch1/magnus/trace_output/primes-fixflo.rkt.out 2>&1
pycket-c wc-fixflo.rkt  >> /scratch1/magnus/trace_output/wc-fixflo.rkt.out 2>&1
pycket-c wc-fixflo.rkt  >> /scratch1/magnus/trace_output/wc-fixflo.rkt.out 2>&1
pycket-c wc-fixflo.rkt  >> /scratch1/magnus/trace_output/wc-fixflo.rkt.out 2>&1
pycket-c takl-nothing.rkt  >> /scratch1/magnus/trace_output/takl-nothing.rkt.out 2>&1
pycket-c takl-nothing.rkt  >> /scratch1/magnus/trace_output/takl-nothing.rkt.out 2>&1
pycket-c takl-nothing.rkt  >> /scratch1/magnus/trace_output/takl-nothing.rkt.out 2>&1
pycket-c mbrot-nothing.rkt  >> /scratch1/magnus/trace_output/mbrot-nothing.rkt.out 2>&1
pycket-c mbrot-nothing.rkt  >> /scratch1/magnus/trace_output/mbrot-nothing.rkt.out 2>&1
pycket-c mbrot-nothing.rkt  >> /scratch1/magnus/trace_output/mbrot-nothing.rkt.out 2>&1
pycket-c nqueens-nothing.rkt  >> /scratch1/magnus/trace_output/nqueens-nothing.rkt.out 2>&1
pycket-c nqueens-nothing.rkt  >> /scratch1/magnus/trace_output/nqueens-nothing.rkt.out 2>&1
pycket-c nqueens-nothing.rkt  >> /scratch1/magnus/trace_output/nqueens-nothing.rkt.out 2>&1
pycket-c parsing-nothing.rkt  >> /scratch1/magnus/trace_output/parsing-nothing.rkt.out 2>&1
pycket-c parsing-nothing.rkt  >> /scratch1/magnus/trace_output/parsing-nothing.rkt.out 2>&1
pycket-c parsing-nothing.rkt  >> /scratch1/magnus/trace_output/parsing-nothing.rkt.out 2>&1
pycket-c scheme-fixflo.rkt  >> /scratch1/magnus/trace_output/scheme-fixflo.rkt.out 2>&1
pycket-c scheme-fixflo.rkt  >> /scratch1/magnus/trace_output/scheme-fixflo.rkt.out 2>&1
pycket-c scheme-fixflo.rkt  >> /scratch1/magnus/trace_output/scheme-fixflo.rkt.out 2>&1
pycket-c triangl-fixflo.rkt  >> /scratch1/magnus/trace_output/triangl-fixflo.rkt.out 2>&1
pycket-c triangl-fixflo.rkt  >> /scratch1/magnus/trace_output/triangl-fixflo.rkt.out 2>&1
pycket-c triangl-fixflo.rkt  >> /scratch1/magnus/trace_output/triangl-fixflo.rkt.out 2>&1
pycket-c sum1-nothing.rkt  >> /scratch1/magnus/trace_output/sum1-nothing.rkt.out 2>&1
pycket-c sum1-nothing.rkt  >> /scratch1/magnus/trace_output/sum1-nothing.rkt.out 2>&1
pycket-c sum1-nothing.rkt  >> /scratch1/magnus/trace_output/sum1-nothing.rkt.out 2>&1
pycket-c takl-fixflo.rkt  >> /scratch1/magnus/trace_output/takl-fixflo.rkt.out 2>&1
pycket-c takl-fixflo.rkt  >> /scratch1/magnus/trace_output/takl-fixflo.rkt.out 2>&1
pycket-c takl-fixflo.rkt  >> /scratch1/magnus/trace_output/takl-fixflo.rkt.out 2>&1
pycket-c fibfp-nothing.rkt  >> /scratch1/magnus/trace_output/fibfp-nothing.rkt.out 2>&1
pycket-c fibfp-nothing.rkt  >> /scratch1/magnus/trace_output/fibfp-nothing.rkt.out 2>&1
pycket-c fibfp-nothing.rkt  >> /scratch1/magnus/trace_output/fibfp-nothing.rkt.out 2>&1
pycket-c sumfp-nothing.rkt  >> /scratch1/magnus/trace_output/sumfp-nothing.rkt.out 2>&1
pycket-c sumfp-nothing.rkt  >> /scratch1/magnus/trace_output/sumfp-nothing.rkt.out 2>&1
pycket-c sumfp-nothing.rkt  >> /scratch1/magnus/trace_output/sumfp-nothing.rkt.out 2>&1
pycket-c puzzle-nothing.rkt  >> /scratch1/magnus/trace_output/puzzle-nothing.rkt.out 2>&1
pycket-c puzzle-nothing.rkt  >> /scratch1/magnus/trace_output/puzzle-nothing.rkt.out 2>&1
pycket-c puzzle-nothing.rkt  >> /scratch1/magnus/trace_output/puzzle-nothing.rkt.out 2>&1
pycket-c destruc-nothing.rkt  >> /scratch1/magnus/trace_output/destruc-nothing.rkt.out 2>&1
pycket-c destruc-nothing.rkt  >> /scratch1/magnus/trace_output/destruc-nothing.rkt.out 2>&1
pycket-c destruc-nothing.rkt  >> /scratch1/magnus/trace_output/destruc-nothing.rkt.out 2>&1
pycket-c perm9-fixflo.rkt  >> /scratch1/magnus/trace_output/perm9-fixflo.rkt.out 2>&1
pycket-c perm9-fixflo.rkt  >> /scratch1/magnus/trace_output/perm9-fixflo.rkt.out 2>&1
pycket-c perm9-fixflo.rkt  >> /scratch1/magnus/trace_output/perm9-fixflo.rkt.out 2>&1
pycket-c cat-nothing.rkt  >> /scratch1/magnus/trace_output/cat-nothing.rkt.out 2>&1
pycket-c cat-nothing.rkt  >> /scratch1/magnus/trace_output/cat-nothing.rkt.out 2>&1
pycket-c cat-nothing.rkt  >> /scratch1/magnus/trace_output/cat-nothing.rkt.out 2>&1
pycket-c fibc-nothing.rkt  >> /scratch1/magnus/trace_output/fibc-nothing.rkt.out 2>&1
pycket-c fibc-nothing.rkt  >> /scratch1/magnus/trace_output/fibc-nothing.rkt.out 2>&1
pycket-c fibc-nothing.rkt  >> /scratch1/magnus/trace_output/fibc-nothing.rkt.out 2>&1
pycket-c fib-nothing.rkt  >> /scratch1/magnus/trace_output/fib-nothing.rkt.out 2>&1
pycket-c fib-nothing.rkt  >> /scratch1/magnus/trace_output/fib-nothing.rkt.out 2>&1
pycket-c fib-nothing.rkt  >> /scratch1/magnus/trace_output/fib-nothing.rkt.out 2>&1
pycket-c nucleic-fixflo.rkt  >> /scratch1/magnus/trace_output/nucleic-fixflo.rkt.out 2>&1
pycket-c nucleic-fixflo.rkt  >> /scratch1/magnus/trace_output/nucleic-fixflo.rkt.out 2>&1
pycket-c nucleic-fixflo.rkt  >> /scratch1/magnus/trace_output/nucleic-fixflo.rkt.out 2>&1
pycket-c matrix-nothing.rkt  >> /scratch1/magnus/trace_output/matrix-nothing.rkt.out 2>&1
pycket-c matrix-nothing.rkt  >> /scratch1/magnus/trace_output/matrix-nothing.rkt.out 2>&1
pycket-c matrix-nothing.rkt  >> /scratch1/magnus/trace_output/matrix-nothing.rkt.out 2>&1
pycket-c diviter-fixflo.rkt  >> /scratch1/magnus/trace_output/diviter-fixflo.rkt.out 2>&1
pycket-c diviter-fixflo.rkt  >> /scratch1/magnus/trace_output/diviter-fixflo.rkt.out 2>&1
pycket-c diviter-fixflo.rkt  >> /scratch1/magnus/trace_output/diviter-fixflo.rkt.out 2>&1
pycket-c boyer-nothing.rkt  >> /scratch1/magnus/trace_output/boyer-nothing.rkt.out 2>&1
pycket-c boyer-nothing.rkt  >> /scratch1/magnus/trace_output/boyer-nothing.rkt.out 2>&1
pycket-c boyer-nothing.rkt  >> /scratch1/magnus/trace_output/boyer-nothing.rkt.out 2>&1
pycket-c sumloop-fixflo.rkt  >> /scratch1/magnus/trace_output/sumloop-fixflo.rkt.out 2>&1
pycket-c sumloop-fixflo.rkt  >> /scratch1/magnus/trace_output/sumloop-fixflo.rkt.out 2>&1
pycket-c sumloop-fixflo.rkt  >> /scratch1/magnus/trace_output/sumloop-fixflo.rkt.out 2>&1
pycket-c dynamic-nothing.rkt  >> /scratch1/magnus/trace_output/dynamic-nothing.rkt.out 2>&1
pycket-c dynamic-nothing.rkt  >> /scratch1/magnus/trace_output/dynamic-nothing.rkt.out 2>&1
pycket-c dynamic-nothing.rkt  >> /scratch1/magnus/trace_output/dynamic-nothing.rkt.out 2>&1
pycket-c array1-fixflo.rkt  >> /scratch1/magnus/trace_output/array1-fixflo.rkt.out 2>&1
pycket-c array1-fixflo.rkt  >> /scratch1/magnus/trace_output/array1-fixflo.rkt.out 2>&1
pycket-c array1-fixflo.rkt  >> /scratch1/magnus/trace_output/array1-fixflo.rkt.out 2>&1
pycket-c deriv-fixflo.rkt  >> /scratch1/magnus/trace_output/deriv-fixflo.rkt.out 2>&1
pycket-c deriv-fixflo.rkt  >> /scratch1/magnus/trace_output/deriv-fixflo.rkt.out 2>&1
pycket-c deriv-fixflo.rkt  >> /scratch1/magnus/trace_output/deriv-fixflo.rkt.out 2>&1
pycket-c nucleic-nothing.rkt  >> /scratch1/magnus/trace_output/nucleic-nothing.rkt.out 2>&1
pycket-c nucleic-nothing.rkt  >> /scratch1/magnus/trace_output/nucleic-nothing.rkt.out 2>&1
pycket-c nucleic-nothing.rkt  >> /scratch1/magnus/trace_output/nucleic-nothing.rkt.out 2>&1
pycket-c ray-fixflo.rkt  >> /scratch1/magnus/trace_output/ray-fixflo.rkt.out 2>&1
pycket-c ray-fixflo.rkt  >> /scratch1/magnus/trace_output/ray-fixflo.rkt.out 2>&1
pycket-c ray-fixflo.rkt  >> /scratch1/magnus/trace_output/ray-fixflo.rkt.out 2>&1
pycket-c nboyer-fixflo.rkt  >> /scratch1/magnus/trace_output/nboyer-fixflo.rkt.out 2>&1
pycket-c nboyer-fixflo.rkt  >> /scratch1/magnus/trace_output/nboyer-fixflo.rkt.out 2>&1
pycket-c nboyer-fixflo.rkt  >> /scratch1/magnus/trace_output/nboyer-fixflo.rkt.out 2>&1
pycket-c puzzle-fixflo.rkt  >> /scratch1/magnus/trace_output/puzzle-fixflo.rkt.out 2>&1
pycket-c puzzle-fixflo.rkt  >> /scratch1/magnus/trace_output/puzzle-fixflo.rkt.out 2>&1
pycket-c puzzle-fixflo.rkt  >> /scratch1/magnus/trace_output/puzzle-fixflo.rkt.out 2>&1
pycket-c diviter-nothing.rkt  >> /scratch1/magnus/trace_output/diviter-nothing.rkt.out 2>&1
pycket-c diviter-nothing.rkt  >> /scratch1/magnus/trace_output/diviter-nothing.rkt.out 2>&1
pycket-c diviter-nothing.rkt  >> /scratch1/magnus/trace_output/diviter-nothing.rkt.out 2>&1
pycket-c paraffins-fixflo.rkt  >> /scratch1/magnus/trace_output/paraffins-fixflo.rkt.out 2>&1
pycket-c paraffins-fixflo.rkt  >> /scratch1/magnus/trace_output/paraffins-fixflo.rkt.out 2>&1
pycket-c paraffins-fixflo.rkt  >> /scratch1/magnus/trace_output/paraffins-fixflo.rkt.out 2>&1
pycket-c dderiv-nothing.rkt  >> /scratch1/magnus/trace_output/dderiv-nothing.rkt.out 2>&1
pycket-c dderiv-nothing.rkt  >> /scratch1/magnus/trace_output/dderiv-nothing.rkt.out 2>&1
pycket-c dderiv-nothing.rkt  >> /scratch1/magnus/trace_output/dderiv-nothing.rkt.out 2>&1
pycket-c browse-fixflo.rkt  >> /scratch1/magnus/trace_output/browse-fixflo.rkt.out 2>&1
pycket-c browse-fixflo.rkt  >> /scratch1/magnus/trace_output/browse-fixflo.rkt.out 2>&1
pycket-c browse-fixflo.rkt  >> /scratch1/magnus/trace_output/browse-fixflo.rkt.out 2>&1
pycket-c pi-nothing.rkt  >> /scratch1/magnus/trace_output/pi-nothing.rkt.out 2>&1
pycket-c pi-nothing.rkt  >> /scratch1/magnus/trace_output/pi-nothing.rkt.out 2>&1
pycket-c pi-nothing.rkt  >> /scratch1/magnus/trace_output/pi-nothing.rkt.out 2>&1
pycket-c earley-nothing.rkt  >> /scratch1/magnus/trace_output/earley-nothing.rkt.out 2>&1
pycket-c earley-nothing.rkt  >> /scratch1/magnus/trace_output/earley-nothing.rkt.out 2>&1
pycket-c earley-nothing.rkt  >> /scratch1/magnus/trace_output/earley-nothing.rkt.out 2>&1
pycket-c dynamic-fixflo.rkt  >> /scratch1/magnus/trace_output/dynamic-fixflo.rkt.out 2>&1
pycket-c dynamic-fixflo.rkt  >> /scratch1/magnus/trace_output/dynamic-fixflo.rkt.out 2>&1
pycket-c dynamic-fixflo.rkt  >> /scratch1/magnus/trace_output/dynamic-fixflo.rkt.out 2>&1
pycket-c ctak-nothing.rkt  >> /scratch1/magnus/trace_output/ctak-nothing.rkt.out 2>&1
pycket-c ctak-nothing.rkt  >> /scratch1/magnus/trace_output/ctak-nothing.rkt.out 2>&1
pycket-c ctak-nothing.rkt  >> /scratch1/magnus/trace_output/ctak-nothing.rkt.out 2>&1
pycket-c divrec-nothing.rkt  >> /scratch1/magnus/trace_output/divrec-nothing.rkt.out 2>&1
pycket-c divrec-nothing.rkt  >> /scratch1/magnus/trace_output/divrec-nothing.rkt.out 2>&1
pycket-c divrec-nothing.rkt  >> /scratch1/magnus/trace_output/divrec-nothing.rkt.out 2>&1
pycket-c fibfp-fixflo.rkt  >> /scratch1/magnus/trace_output/fibfp-fixflo.rkt.out 2>&1
pycket-c fibfp-fixflo.rkt  >> /scratch1/magnus/trace_output/fibfp-fixflo.rkt.out 2>&1
pycket-c fibfp-fixflo.rkt  >> /scratch1/magnus/trace_output/fibfp-fixflo.rkt.out 2>&1
pycket-c simplex-fixflo.rkt  >> /scratch1/magnus/trace_output/simplex-fixflo.rkt.out 2>&1
pycket-c simplex-fixflo.rkt  >> /scratch1/magnus/trace_output/simplex-fixflo.rkt.out 2>&1
pycket-c simplex-fixflo.rkt  >> /scratch1/magnus/trace_output/simplex-fixflo.rkt.out 2>&1
pycket-c ack-nothing.rkt  >> /scratch1/magnus/trace_output/ack-nothing.rkt.out 2>&1
pycket-c ack-nothing.rkt  >> /scratch1/magnus/trace_output/ack-nothing.rkt.out 2>&1
pycket-c ack-nothing.rkt  >> /scratch1/magnus/trace_output/ack-nothing.rkt.out 2>&1
pycket-c destruc-fixflo.rkt  >> /scratch1/magnus/trace_output/destruc-fixflo.rkt.out 2>&1
pycket-c destruc-fixflo.rkt  >> /scratch1/magnus/trace_output/destruc-fixflo.rkt.out 2>&1
pycket-c destruc-fixflo.rkt  >> /scratch1/magnus/trace_output/destruc-fixflo.rkt.out 2>&1
pycket-c tail-nothing.rkt  >> /scratch1/magnus/trace_output/tail-nothing.rkt.out 2>&1
pycket-c tail-nothing.rkt  >> /scratch1/magnus/trace_output/tail-nothing.rkt.out 2>&1
pycket-c tail-nothing.rkt  >> /scratch1/magnus/trace_output/tail-nothing.rkt.out 2>&1
pycket-c fibc-fixflo.rkt  >> /scratch1/magnus/trace_output/fibc-fixflo.rkt.out 2>&1
pycket-c fibc-fixflo.rkt  >> /scratch1/magnus/trace_output/fibc-fixflo.rkt.out 2>&1
pycket-c fibc-fixflo.rkt  >> /scratch1/magnus/trace_output/fibc-fixflo.rkt.out 2>&1
pycket-c nboyer-nothing.rkt  >> /scratch1/magnus/trace_output/nboyer-nothing.rkt.out 2>&1
pycket-c nboyer-nothing.rkt  >> /scratch1/magnus/trace_output/nboyer-nothing.rkt.out 2>&1
pycket-c nboyer-nothing.rkt  >> /scratch1/magnus/trace_output/nboyer-nothing.rkt.out 2>&1
pycket-c conform-nothing.rkt  >> /scratch1/magnus/trace_output/conform-nothing.rkt.out 2>&1
pycket-c conform-nothing.rkt  >> /scratch1/magnus/trace_output/conform-nothing.rkt.out 2>&1
pycket-c conform-nothing.rkt  >> /scratch1/magnus/trace_output/conform-nothing.rkt.out 2>&1
pycket-c maze-nothing.rkt  >> /scratch1/magnus/trace_output/maze-nothing.rkt.out 2>&1
pycket-c maze-nothing.rkt  >> /scratch1/magnus/trace_output/maze-nothing.rkt.out 2>&1
pycket-c maze-nothing.rkt  >> /scratch1/magnus/trace_output/maze-nothing.rkt.out 2>&1
pycket-c sboyer-fixflo.rkt  >> /scratch1/magnus/trace_output/sboyer-fixflo.rkt.out 2>&1
pycket-c sboyer-fixflo.rkt  >> /scratch1/magnus/trace_output/sboyer-fixflo.rkt.out 2>&1
pycket-c sboyer-fixflo.rkt  >> /scratch1/magnus/trace_output/sboyer-fixflo.rkt.out 2>&1
pycket-c matrix-fixflo.rkt  >> /scratch1/magnus/trace_output/matrix-fixflo.rkt.out 2>&1
pycket-c matrix-fixflo.rkt  >> /scratch1/magnus/trace_output/matrix-fixflo.rkt.out 2>&1
pycket-c matrix-fixflo.rkt  >> /scratch1/magnus/trace_output/matrix-fixflo.rkt.out 2>&1
pycket-c boyer-fixflo.rkt  >> /scratch1/magnus/trace_output/boyer-fixflo.rkt.out 2>&1
pycket-c boyer-fixflo.rkt  >> /scratch1/magnus/trace_output/boyer-fixflo.rkt.out 2>&1
pycket-c boyer-fixflo.rkt  >> /scratch1/magnus/trace_output/boyer-fixflo.rkt.out 2>&1
pycket-c gcbench-fixflo.rkt  >> /scratch1/magnus/trace_output/gcbench-fixflo.rkt.out 2>&1
pycket-c gcbench-fixflo.rkt  >> /scratch1/magnus/trace_output/gcbench-fixflo.rkt.out 2>&1
pycket-c gcbench-fixflo.rkt  >> /scratch1/magnus/trace_output/gcbench-fixflo.rkt.out 2>&1
pycket-c ack-fixflo.rkt  >> /scratch1/magnus/trace_output/ack-fixflo.rkt.out 2>&1
pycket-c ack-fixflo.rkt  >> /scratch1/magnus/trace_output/ack-fixflo.rkt.out 2>&1
pycket-c ack-fixflo.rkt  >> /scratch1/magnus/trace_output/ack-fixflo.rkt.out 2>&1
pycket-c deriv-nothing.rkt  >> /scratch1/magnus/trace_output/deriv-nothing.rkt.out 2>&1
pycket-c deriv-nothing.rkt  >> /scratch1/magnus/trace_output/deriv-nothing.rkt.out 2>&1
pycket-c deriv-nothing.rkt  >> /scratch1/magnus/trace_output/deriv-nothing.rkt.out 2>&1
pycket-c fft-fixflo.rkt  >> /scratch1/magnus/trace_output/fft-fixflo.rkt.out 2>&1
pycket-c fft-fixflo.rkt  >> /scratch1/magnus/trace_output/fft-fixflo.rkt.out 2>&1
pycket-c fft-fixflo.rkt  >> /scratch1/magnus/trace_output/fft-fixflo.rkt.out 2>&1
pycket-c fib-fixflo.rkt  >> /scratch1/magnus/trace_output/fib-fixflo.rkt.out 2>&1
pycket-c fib-fixflo.rkt  >> /scratch1/magnus/trace_output/fib-fixflo.rkt.out 2>&1
pycket-c fib-fixflo.rkt  >> /scratch1/magnus/trace_output/fib-fixflo.rkt.out 2>&1
pycket-c array1-nothing.rkt  >> /scratch1/magnus/trace_output/array1-nothing.rkt.out 2>&1
pycket-c array1-nothing.rkt  >> /scratch1/magnus/trace_output/array1-nothing.rkt.out 2>&1
pycket-c array1-nothing.rkt  >> /scratch1/magnus/trace_output/array1-nothing.rkt.out 2>&1
pycket-c sboyer-nothing.rkt  >> /scratch1/magnus/trace_output/sboyer-nothing.rkt.out 2>&1
pycket-c sboyer-nothing.rkt  >> /scratch1/magnus/trace_output/sboyer-nothing.rkt.out 2>&1
pycket-c sboyer-nothing.rkt  >> /scratch1/magnus/trace_output/sboyer-nothing.rkt.out 2>&1
pycket-c graphs-nothing.rkt  >> /scratch1/magnus/trace_output/graphs-nothing.rkt.out 2>&1
pycket-c graphs-nothing.rkt  >> /scratch1/magnus/trace_output/graphs-nothing.rkt.out 2>&1
pycket-c graphs-nothing.rkt  >> /scratch1/magnus/trace_output/graphs-nothing.rkt.out 2>&1
pycket-c dderiv-fixflo.rkt  >> /scratch1/magnus/trace_output/dderiv-fixflo.rkt.out 2>&1
pycket-c dderiv-fixflo.rkt  >> /scratch1/magnus/trace_output/dderiv-fixflo.rkt.out 2>&1
pycket-c dderiv-fixflo.rkt  >> /scratch1/magnus/trace_output/dderiv-fixflo.rkt.out 2>&1
pycket-c cpstak-nothing.rkt  >> /scratch1/magnus/trace_output/cpstak-nothing.rkt.out 2>&1
pycket-c cpstak-nothing.rkt  >> /scratch1/magnus/trace_output/cpstak-nothing.rkt.out 2>&1
pycket-c cpstak-nothing.rkt  >> /scratch1/magnus/trace_output/cpstak-nothing.rkt.out 2>&1
pycket-c browse-nothing.rkt  >> /scratch1/magnus/trace_output/browse-nothing.rkt.out 2>&1
pycket-c browse-nothing.rkt  >> /scratch1/magnus/trace_output/browse-nothing.rkt.out 2>&1
pycket-c browse-nothing.rkt  >> /scratch1/magnus/trace_output/browse-nothing.rkt.out 2>&1
pycket-c parsing-fixflo.rkt  >> /scratch1/magnus/trace_output/parsing-fixflo.rkt.out 2>&1
pycket-c parsing-fixflo.rkt  >> /scratch1/magnus/trace_output/parsing-fixflo.rkt.out 2>&1
pycket-c parsing-fixflo.rkt  >> /scratch1/magnus/trace_output/parsing-fixflo.rkt.out 2>&1
pycket-c earley-fixflo.rkt  >> /scratch1/magnus/trace_output/earley-fixflo.rkt.out 2>&1
pycket-c earley-fixflo.rkt  >> /scratch1/magnus/trace_output/earley-fixflo.rkt.out 2>&1
pycket-c earley-fixflo.rkt  >> /scratch1/magnus/trace_output/earley-fixflo.rkt.out 2>&1
pycket-c ctak-fixflo.rkt  >> /scratch1/magnus/trace_output/ctak-fixflo.rkt.out 2>&1
pycket-c ctak-fixflo.rkt  >> /scratch1/magnus/trace_output/ctak-fixflo.rkt.out 2>&1
pycket-c ctak-fixflo.rkt  >> /scratch1/magnus/trace_output/ctak-fixflo.rkt.out 2>&1
pycket-c sum1-fixflo.rkt  >> /scratch1/magnus/trace_output/sum1-fixflo.rkt.out 2>&1
pycket-c sum1-fixflo.rkt  >> /scratch1/magnus/trace_output/sum1-fixflo.rkt.out 2>&1
pycket-c sum1-fixflo.rkt  >> /scratch1/magnus/trace_output/sum1-fixflo.rkt.out 2>&1
pycket-c divrec-fixflo.rkt  >> /scratch1/magnus/trace_output/divrec-fixflo.rkt.out 2>&1
pycket-c divrec-fixflo.rkt  >> /scratch1/magnus/trace_output/divrec-fixflo.rkt.out 2>&1
pycket-c divrec-fixflo.rkt  >> /scratch1/magnus/trace_output/divrec-fixflo.rkt.out 2>&1
