pycket-c wc.rkt sumcol-20000 >> /scratch1/magnus/trace_output/wc.rkt.out 2>&1
pycket-c wc.rkt sumcol-20000 >> /scratch1/magnus/trace_output/wc.rkt.out 2>&1
pycket-c wc.rkt sumcol-20000 >> /scratch1/magnus/trace_output/wc.rkt.out 2>&1
pycket-c nsievebits.rkt 12 >> /scratch1/magnus/trace_output/nsievebits.rkt.out 2>&1
pycket-c nsievebits.rkt 12 >> /scratch1/magnus/trace_output/nsievebits.rkt.out 2>&1
pycket-c nsievebits.rkt 12 >> /scratch1/magnus/trace_output/nsievebits.rkt.out 2>&1
pycket-c random.rkt 250000000 >> /scratch1/magnus/trace_output/random.rkt.out 2>&1
pycket-c random.rkt 250000000 >> /scratch1/magnus/trace_output/random.rkt.out 2>&1
pycket-c random.rkt 250000000 >> /scratch1/magnus/trace_output/random.rkt.out 2>&1
pycket-c ary.rkt 1700000 >> /scratch1/magnus/trace_output/ary.rkt.out 2>&1
pycket-c ary.rkt 1700000 >> /scratch1/magnus/trace_output/ary.rkt.out 2>&1
pycket-c ary.rkt 1700000 >> /scratch1/magnus/trace_output/ary.rkt.out 2>&1
pycket-c meteor.rkt 200000 >> /scratch1/magnus/trace_output/meteor.rkt.out 2>&1
pycket-c meteor.rkt 200000 >> /scratch1/magnus/trace_output/meteor.rkt.out 2>&1
pycket-c meteor.rkt 200000 >> /scratch1/magnus/trace_output/meteor.rkt.out 2>&1
pycket-c wc.rkt sumcol-20000 >> /scratch1/magnus/trace_output/wc.rkt.out 2>&1
pycket-c wc.rkt sumcol-20000 >> /scratch1/magnus/trace_output/wc.rkt.out 2>&1
pycket-c wc.rkt sumcol-20000 >> /scratch1/magnus/trace_output/wc.rkt.out 2>&1
pycket-c nbody-generic.rkt 8000000 >> /scratch1/magnus/trace_output/nbody-generic.rkt.out 2>&1
pycket-c nbody-generic.rkt 8000000 >> /scratch1/magnus/trace_output/nbody-generic.rkt.out 2>&1
pycket-c nbody-generic.rkt 8000000 >> /scratch1/magnus/trace_output/nbody-generic.rkt.out 2>&1
pycket-c lists.rkt 2000 >> /scratch1/magnus/trace_output/lists.rkt.out 2>&1
pycket-c lists.rkt 2000 >> /scratch1/magnus/trace_output/lists.rkt.out 2>&1
pycket-c lists.rkt 2000 >> /scratch1/magnus/trace_output/lists.rkt.out 2>&1
pycket-c nestedloop.rkt 35 >> /scratch1/magnus/trace_output/nestedloop.rkt.out 2>&1
pycket-c nestedloop.rkt 35 >> /scratch1/magnus/trace_output/nestedloop.rkt.out 2>&1
pycket-c nestedloop.rkt 35 >> /scratch1/magnus/trace_output/nestedloop.rkt.out 2>&1
pycket-c binarytrees.rkt 17 >> /scratch1/magnus/trace_output/binarytrees.rkt.out 2>&1
pycket-c binarytrees.rkt 17 >> /scratch1/magnus/trace_output/binarytrees.rkt.out 2>&1
pycket-c binarytrees.rkt 17 >> /scratch1/magnus/trace_output/binarytrees.rkt.out 2>&1
pycket-c sieve.rkt 50000 >> /scratch1/magnus/trace_output/sieve.rkt.out 2>&1
pycket-c sieve.rkt 50000 >> /scratch1/magnus/trace_output/sieve.rkt.out 2>&1
pycket-c sieve.rkt 50000 >> /scratch1/magnus/trace_output/sieve.rkt.out 2>&1
pycket-c ackermann.rkt 12 >> /scratch1/magnus/trace_output/ackermann.rkt.out 2>&1
pycket-c ackermann.rkt 12 >> /scratch1/magnus/trace_output/ackermann.rkt.out 2>&1
pycket-c ackermann.rkt 12 >> /scratch1/magnus/trace_output/ackermann.rkt.out 2>&1
pycket-c partialsums.rkt 15000000 >> /scratch1/magnus/trace_output/partialsums.rkt.out 2>&1
pycket-c partialsums.rkt 15000000 >> /scratch1/magnus/trace_output/partialsums.rkt.out 2>&1
pycket-c partialsums.rkt 15000000 >> /scratch1/magnus/trace_output/partialsums.rkt.out 2>&1
pycket-c pidigits1.rkt 20000 >> /scratch1/magnus/trace_output/pidigits1.rkt.out 2>&1
pycket-c pidigits1.rkt 20000 >> /scratch1/magnus/trace_output/pidigits1.rkt.out 2>&1
pycket-c pidigits1.rkt 20000 >> /scratch1/magnus/trace_output/pidigits1.rkt.out 2>&1
pycket-c moments.rkt moments-2000 >> /scratch1/magnus/trace_output/moments.rkt.out 2>&1
pycket-c moments.rkt moments-2000 >> /scratch1/magnus/trace_output/moments.rkt.out 2>&1
pycket-c moments.rkt moments-2000 >> /scratch1/magnus/trace_output/moments.rkt.out 2>&1
pycket-c fannkuch-redux.rkt 10 >> /scratch1/magnus/trace_output/fannkuch-redux.rkt.out 2>&1
pycket-c fannkuch-redux.rkt 10 >> /scratch1/magnus/trace_output/fannkuch-redux.rkt.out 2>&1
pycket-c fannkuch-redux.rkt 10 >> /scratch1/magnus/trace_output/fannkuch-redux.rkt.out 2>&1
pycket-c nbody.rkt 8000000 >> /scratch1/magnus/trace_output/nbody.rkt.out 2>&1
pycket-c nbody.rkt 8000000 >> /scratch1/magnus/trace_output/nbody.rkt.out 2>&1
pycket-c nbody.rkt 8000000 >> /scratch1/magnus/trace_output/nbody.rkt.out 2>&1
pycket-c pidigits.rkt 7000 >> /scratch1/magnus/trace_output/pidigits.rkt.out 2>&1
pycket-c pidigits.rkt 7000 >> /scratch1/magnus/trace_output/pidigits.rkt.out 2>&1
pycket-c pidigits.rkt 7000 >> /scratch1/magnus/trace_output/pidigits.rkt.out 2>&1
pycket-c fannkuch.rkt 10 >> /scratch1/magnus/trace_output/fannkuch.rkt.out 2>&1
pycket-c fannkuch.rkt 10 >> /scratch1/magnus/trace_output/fannkuch.rkt.out 2>&1
pycket-c fannkuch.rkt 10 >> /scratch1/magnus/trace_output/fannkuch.rkt.out 2>&1
pycket-c recursive.rkt 12 >> /scratch1/magnus/trace_output/recursive.rkt.out 2>&1
pycket-c recursive.rkt 12 >> /scratch1/magnus/trace_output/recursive.rkt.out 2>&1
pycket-c recursive.rkt 12 >> /scratch1/magnus/trace_output/recursive.rkt.out 2>&1
pycket-c hash.rkt 4000000 >> /scratch1/magnus/trace_output/hash.rkt.out 2>&1
pycket-c hash.rkt 4000000 >> /scratch1/magnus/trace_output/hash.rkt.out 2>&1
pycket-c hash.rkt 4000000 >> /scratch1/magnus/trace_output/hash.rkt.out 2>&1
pycket-c spectralnorm.rkt 3000 >> /scratch1/magnus/trace_output/spectralnorm.rkt.out 2>&1
pycket-c spectralnorm.rkt 3000 >> /scratch1/magnus/trace_output/spectralnorm.rkt.out 2>&1
pycket-c spectralnorm.rkt 3000 >> /scratch1/magnus/trace_output/spectralnorm.rkt.out 2>&1
pycket-c mandelbrot.rkt 5000 >> /scratch1/magnus/trace_output/mandelbrot.rkt.out 2>&1
pycket-c mandelbrot.rkt 5000 >> /scratch1/magnus/trace_output/mandelbrot.rkt.out 2>&1
pycket-c mandelbrot.rkt 5000 >> /scratch1/magnus/trace_output/mandelbrot.rkt.out 2>&1
pycket-c spellcheck.rkt ulysses >> /scratch1/magnus/trace_output/spellcheck.rkt.out 2>&1
pycket-c spellcheck.rkt ulysses >> /scratch1/magnus/trace_output/spellcheck.rkt.out 2>&1
pycket-c spellcheck.rkt ulysses >> /scratch1/magnus/trace_output/spellcheck.rkt.out 2>&1
pycket-c hash2.rkt 6000 >> /scratch1/magnus/trace_output/hash2.rkt.out 2>&1
pycket-c hash2.rkt 6000 >> /scratch1/magnus/trace_output/hash2.rkt.out 2>&1
pycket-c hash2.rkt 6000 >> /scratch1/magnus/trace_output/hash2.rkt.out 2>&1
pycket-c nbody-vec-generic.rkt 15000000 >> /scratch1/magnus/trace_output/nbody-vec-generic.rkt.out 2>&1
pycket-c nbody-vec-generic.rkt 15000000 >> /scratch1/magnus/trace_output/nbody-vec-generic.rkt.out 2>&1
pycket-c nbody-vec-generic.rkt 15000000 >> /scratch1/magnus/trace_output/nbody-vec-generic.rkt.out 2>&1
pycket-c fannkuch-redux-generic.rkt 10 >> /scratch1/magnus/trace_output/fannkuch-redux-generic.rkt.out 2>&1
pycket-c fannkuch-redux-generic.rkt 10 >> /scratch1/magnus/trace_output/fannkuch-redux-generic.rkt.out 2>&1
pycket-c fannkuch-redux-generic.rkt 10 >> /scratch1/magnus/trace_output/fannkuch-redux-generic.rkt.out 2>&1
pycket-c sumcol.rkt sumcol-20000 >> /scratch1/magnus/trace_output/sumcol.rkt.out 2>&1
pycket-c sumcol.rkt sumcol-20000 >> /scratch1/magnus/trace_output/sumcol.rkt.out 2>&1
pycket-c sumcol.rkt sumcol-20000 >> /scratch1/magnus/trace_output/sumcol.rkt.out 2>&1
pycket-c strcat.rkt 110000000 >> /scratch1/magnus/trace_output/strcat.rkt.out 2>&1
pycket-c strcat.rkt 110000000 >> /scratch1/magnus/trace_output/strcat.rkt.out 2>&1
pycket-c strcat.rkt 110000000 >> /scratch1/magnus/trace_output/strcat.rkt.out 2>&1
pycket-c matrix.rkt 25000 >> /scratch1/magnus/trace_output/matrix.rkt.out 2>&1
pycket-c matrix.rkt 25000 >> /scratch1/magnus/trace_output/matrix.rkt.out 2>&1
pycket-c matrix.rkt 25000 >> /scratch1/magnus/trace_output/matrix.rkt.out 2>&1
pycket-c fibo.rkt 42 >> /scratch1/magnus/trace_output/fibo.rkt.out 2>&1
pycket-c fibo.rkt 42 >> /scratch1/magnus/trace_output/fibo.rkt.out 2>&1
pycket-c fibo.rkt 42 >> /scratch1/magnus/trace_output/fibo.rkt.out 2>&1
pycket-c spectralnorm-generic.rkt 3000 >> /scratch1/magnus/trace_output/spectralnorm-generic.rkt.out 2>&1
pycket-c spectralnorm-generic.rkt 3000 >> /scratch1/magnus/trace_output/spectralnorm-generic.rkt.out 2>&1
pycket-c spectralnorm-generic.rkt 3000 >> /scratch1/magnus/trace_output/spectralnorm-generic.rkt.out 2>&1
pycket-c regexmatch.rkt regexmatch-1000000 >> /scratch1/magnus/trace_output/regexmatch.rkt.out 2>&1
pycket-c regexmatch.rkt regexmatch-1000000 >> /scratch1/magnus/trace_output/regexmatch.rkt.out 2>&1
pycket-c regexmatch.rkt regexmatch-1000000 >> /scratch1/magnus/trace_output/regexmatch.rkt.out 2>&1
pycket-c wordfreq.rkt sumcol-20000 >> /scratch1/magnus/trace_output/wordfreq.rkt.out 2>&1
pycket-c wordfreq.rkt sumcol-20000 >> /scratch1/magnus/trace_output/wordfreq.rkt.out 2>&1
pycket-c wordfreq.rkt sumcol-20000 >> /scratch1/magnus/trace_output/wordfreq.rkt.out 2>&1
pycket-c heapsort.rkt 1500000 >> /scratch1/magnus/trace_output/heapsort.rkt.out 2>&1
pycket-c heapsort.rkt 1500000 >> /scratch1/magnus/trace_output/heapsort.rkt.out 2>&1
pycket-c heapsort.rkt 1500000 >> /scratch1/magnus/trace_output/heapsort.rkt.out 2>&1
pycket-c nsieve.rkt 12 >> /scratch1/magnus/trace_output/nsieve.rkt.out 2>&1
pycket-c nsieve.rkt 12 >> /scratch1/magnus/trace_output/nsieve.rkt.out 2>&1
pycket-c nsieve.rkt 12 >> /scratch1/magnus/trace_output/nsieve.rkt.out 2>&1
pycket-c nbody-vec.rkt 15000000 >> /scratch1/magnus/trace_output/nbody-vec.rkt.out 2>&1
pycket-c nbody-vec.rkt 15000000 >> /scratch1/magnus/trace_output/nbody-vec.rkt.out 2>&1
pycket-c nbody-vec.rkt 15000000 >> /scratch1/magnus/trace_output/nbody-vec.rkt.out 2>&1
pycket-c binarytrees-generic.rkt 17 >> /scratch1/magnus/trace_output/binarytrees-generic.rkt.out 2>&1
pycket-c binarytrees-generic.rkt 17 >> /scratch1/magnus/trace_output/binarytrees-generic.rkt.out 2>&1
pycket-c binarytrees-generic.rkt 17 >> /scratch1/magnus/trace_output/binarytrees-generic.rkt.out 2>&1
pycket-c mandelbrot-generic.rkt 5000 >> /scratch1/magnus/trace_output/mandelbrot-generic.rkt.out 2>&1
pycket-c mandelbrot-generic.rkt 5000 >> /scratch1/magnus/trace_output/mandelbrot-generic.rkt.out 2>&1
pycket-c mandelbrot-generic.rkt 5000 >> /scratch1/magnus/trace_output/mandelbrot-generic.rkt.out 2>&1
